server:
    port: 8080
wave:
    domain: localhost
    contextPath: MinD_banker_wave
spring:
    thymeleaf:
        cache: false
        enabled: true
        prefix: classpath:/templates/
        suffix: .html
        encoding: UTF-8
        check-template: true
        check-template-location: true

    application:
        name: ContainerList

logging:
    level:
        root: INFO
